services:
  web:
    build: .
    ports:
    - "9012:80"
    restart: always
    environment:
    - FLAG=LKSN{jangan_ya_dek_ya__jangan_buka_web_semacam_ini_ya_dek_ya}
    volumes:
    - "./src:/var/www/html"